create table
    public.date_dim
    (
        date_key integer not null,
        full_dt date,
        prev_full_dt date,
        prev_7_full_dt date,
        prev_30_full_dt date,
        prev_60_full_dt date,
        prev_90_full_dt date,
        prev_120_full_dt date,
        day_of_week_name character varying(10),
        day_of_week_mo_su_num smallint,
        day_of_week_su_sa_num smallint,
        day_of_month_num smallint,
        day_of_year_num smallint,
        days_left_in_week smallint,
        days_left_in_month smallint,
        days_left_in_year smallint,
        fed_business_day_fl character(1),
        fed_holiday_fl character(1),
        fed_business_day_num integer,
        prev_fed_business_day_num integer,
        last_day_of_month_fl character(1),
        fed_next_biz_full_dt date,
        fed_prev_biz_full_dt date,
        unix_days integer,
        unix_start_secs BIGINT,
        unix_end_secs BIGINT,
        weekday_fl character(1),
        week_su_sa_id integer,
        week_in_year_su_sa_num smallint,
        prev_week_in_year_su_sa_num smallint,
        week_su_sa_start_dt date,
        week_su_sa_end_dt date,
        week_mo_su_id integer,
        week_in_month_mo_su_num smallint,
        prev_week_in_month_mo_su_num smallint,
        week_in_year_mo_su_num smallint,
        prev_week_in_year_mo_su_num smallint,
        week_mo_su_start_dt date,
        week_mo_su_end_dt date,
        month_id integer,
        prev_month_id integer,
        prev_three_month_id integer,
        prev_six_month_id integer,
        prev_nine_month_id integer,
        prev_twelve_month_id integer,
        month_dt date,
        month_end_dt date,
        ldom_01_back_dt date,
        ldom_03_back_dt date,
        ldom_06_back_dt date,
        ldom_12_back_dt date,
        month_name character varying(10),
        month_full_short_name character varying(200),
        month_full_long_name character varying(200),
        month_num smallint,
        prev_month_num smallint,
        number_of_days_in_month smallint,
        quarter_id integer,
        quarter_num smallint,
        prev_quarter_num smallint,
        quarter_full_name character varying(26),
        number_of_days_in_quarter smallint,
        year integer,
        prev_year integer,
        fed_business_day_soy integer,
        fed_business_day_eoy integer,
        year_start_dt date,
        year_end_dt date,
        number_of_days_in_year smallint,
        constraint date_dim_pk primary key (date_key)
    );